---
kind: pipeline
type: docker
name: default

steps:
- name: check code complexity
  image: python:3.9
  commands:
  - pip install radon
  - ./code_quality.sh

- name: check pep8 formatting
  image: python:3.9
  when:
    branch: master
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash code_pep8.sh

- name: install, build doc run scripts
  image: python:3.8
  commands:
  - pip install Cython
  - git fetch --tags 
  - python setup.py install
  - pip install sphinx sphinx_rtd_theme
  - cd doc
  - make html
  - cd ../scripts
  - coverage run --source genmechanics ci_scripts.py
  - coverage json
  - coverage report
  - python coverage.py

- name: develop
  image: python:3.8
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist, bdist
  image: python:3.8
  commands:
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: notify
  when:
    status:
    - failure 
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
